#!/usr/bin/env python3
"""Generate the checked-in C++ resource table used by dingo-mds."""
from __future__ import annotations

import hashlib
import mimetypes
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DIST = ROOT / "console" / "dist"
OUT = ROOT / "src" / "mds" / "service"

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
}


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate() -> None:
    if not DIST.exists():
        raise SystemExit(f"missing build output: {DIST}; run npm run build first")
    files = sorted(path for path in DIST.rglob("*") if path.is_file() and path.suffix != ".map")
    if not any(path.name == "index.html" for path in files):
        raise SystemExit("build output does not contain index.html")

    declarations: list[str] = []
    entries: list[str] = []
    for index, path in enumerate(files):
        relative = path.relative_to(DIST).as_posix()
        data = path.read_bytes()
        digest = hashlib.sha256(data).hexdigest()[:16]
        array_name = f"kAssetData{index}"
        declarations.append(f"static const unsigned char {array_name}[] = {{")
        for offset in range(0, len(data), 24):
            declarations.append("  " + ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 24]) + ",")
        declarations.append("};")
        content_type = CONTENT_TYPES.get(path.suffix, mimetypes.guess_type(path.name)[0] or "application/octet-stream")
        entries.append(
            "  {" + ", ".join(
                [cpp_string(relative), array_name, str(len(data)), cpp_string(content_type), cpp_string(f'"{digest}"')]
            ) + "},"
        )

    generated = """// Generated by console/scripts/generate_assets.py. DO NOT EDIT.\n\n#include \"mds/service/fsstat_assets.h\"\n\nnamespace dingofs {\nnamespace mds {\nnamespace {\n\n"""
    generated += "\n".join(declarations)
    generated += "\n\nstatic const FsStatAsset kAssets[] = {\n"
    generated += "\n".join(entries)
    generated += """\n};\n\n}  // namespace\n\nconst FsStatAsset* FindFsStatAsset(std::string_view path) {\n  for (const auto& asset : kAssets) {\n    if (asset.path == path) return &asset;\n  }\n  return nullptr;\n}\n\n}  // namespace mds\n}  // namespace dingofs\n"""
    (OUT / "fsstat_assets_generated.cc").write_text(generated)
    print(f"generated {len(files)} assets")


if __name__ == "__main__":
    generate()
