/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFilesystems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mds-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMdsNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache-members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCacheMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFilesystemQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/dir-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDirectoryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/mountpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMountpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/file-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFileSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/files/{ino}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/files/{ino}/shard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPartitionShard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getServerDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersionInformation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDistributionLocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/id-generators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIdGenerators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCacheSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/parse-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["parseMetadataKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFilesystemDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDirectoryEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/deleted-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeletedFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/deleted-files/{ino}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeletedFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/deleted-slices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeletedSlices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/slice-references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSliceReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/oplog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFilesystemOpLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesystems/{fsId}/inodes/{ino}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInodeDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                requestId: string;
            };
        };
        RemainingResponse: {
            /** Format: date-time */
            generatedAt: string;
            items?: unknown[];
        } & {
            [key: string]: unknown;
        };
        DiagnosticResponse: {
            filesystemId: string;
            ino?: string;
            /** Format: date-time */
            generatedAt: string;
        } & {
            [key: string]: unknown;
        };
        Overview: {
            clusterId: string;
            servingMdsId: string;
            storageEngine: string;
            apiVersion: string;
            build: {
                version: string;
                commit: string;
                commitTime: string;
            };
        };
        ListMeta: {
            items: unknown[];
            /** Format: date-time */
            generatedAt: string;
            nextCursor: string | null;
            truncated?: boolean;
        };
        Summary: {
            [key: string]: number;
        };
        FilesystemCollection: components["schemas"]["ListMeta"] & {
            summary?: components["schemas"]["Summary"];
            items?: components["schemas"]["Filesystem"][];
        };
        MdsCollection: components["schemas"]["ListMeta"] & {
            summary?: components["schemas"]["Summary"];
            items?: components["schemas"]["MdsNode"][];
        };
        ClientCollection: components["schemas"]["ListMeta"] & {
            summary?: components["schemas"]["Summary"];
            items?: components["schemas"]["Client"][];
        };
        CacheMemberCollection: components["schemas"]["ListMeta"] & {
            summary?: components["schemas"]["Summary"];
            items?: components["schemas"]["CacheMember"][];
        };
        Health: {
            state: string;
            reason: string;
        };
        Filesystem: {
            id: string;
            name: string;
            lifecycleState: string;
            type: string;
            partitionType: string;
            owner: string;
            capacityBytes: string;
            blockSizeBytes?: string;
            chunkSizeBytes?: string;
            mountPointCount: number;
            uuid?: string;
            version?: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt?: string;
            health: components["schemas"]["Health"];
            storage?: {
                type?: string;
                endpoint?: string;
                bucket?: string;
                pool?: string;
                cluster?: string;
            };
        };
        MdsNode: {
            id: string;
            host: string;
            port: number;
            state: string;
            health: components["schemas"]["Health"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastOnlineAt: string;
        };
        Client: {
            id: string;
            host: string;
            hostname?: string;
            port: number;
            mountpoint: string;
            filesystem: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastOnlineAt?: string;
            health: components["schemas"]["Health"];
        };
        CacheMember: {
            id: string;
            host: string;
            group: string;
            weight: number;
            locked: boolean;
            state: string;
            /** Format: date-time */
            lastOnlineAt?: string;
            health: components["schemas"]["Health"];
        };
    };
    responses: {
        /** @description A required MDS dependency is unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Limit: number;
        Cursor: string;
        FsId: string;
        Ino: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Console metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    getFilesystems: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File system collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilesystemCollection"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getMdsNodes: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MDS node collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MdsCollection"];
                };
            };
        };
    };
    getClients: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientCollection"];
                };
            };
        };
    };
    getCacheMembers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache member collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheMemberCollection"];
                };
            };
        };
    };
    getFilesystemQuota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File-system and directory quota. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
        };
    };
    getDirectoryStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
        };
    };
    getMountpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File-system mount points. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
        };
    };
    getFileSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open file sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
        };
    };
    getChunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
                ino: components["parameters"]["Ino"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File chunks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
        };
    };
    getPartitionShard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
                ino: components["parameters"]["Ino"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Partition shard description. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
        };
    };
    getServerDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server diagnostic details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getVersionInformation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build and SDK versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getDistributionLocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distribution lock leases. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getIdGenerators: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ID generator descriptions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getCacheSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MDS cache summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    parseMetadataKey: {
        parameters: {
            query?: {
                key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parsed metadata key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getFilesystemDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allowlisted file-system details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getDirectoryEntries: {
        parameters: {
            query?: {
                parentIno?: string;
            };
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded directory entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getDeletedFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted inode collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getDeletedFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
                ino: components["parameters"]["Ino"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted inode details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getDeletedSlices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted slice collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getSliceReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slice reference collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getFilesystemOpLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File-system operation log. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
    getInodeDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fsId: components["parameters"]["FsId"];
                ino: components["parameters"]["Ino"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inode details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingResponse"];
                };
            };
        };
    };
}
